"""Criar habilidade

Revision ID: 5e547ea81d68
Revises: ecd77292847f
Create Date: 2025-11-11 13:20:21.182484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e547ea81d68'
down_revision = 'ecd77292847f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('voluntario_habilidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_habilidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_habilidade'], ['habilidade.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'id_habilidade', name='uq_usuario_habilidade')
    )
    op.create_table('oportunidade_habilidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_oportunidade', sa.Integer(), nullable=False),
    sa.Column('id_habilidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_habilidade'], ['habilidade.id'], ),
    sa.ForeignKeyConstraint(['id_oportunidade'], ['oportunidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_oportunidade', 'id_habilidade', name='uq_oportunidade_habilidade')
    )
    op.create_table('registro_presenca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_inscricao', sa.Integer(), nullable=False),
    sa.Column('codigo_validacao_pin', sa.String(length=100), nullable=False),
    sa.Column('check_in_hora', sa.DateTime(), nullable=True),
    sa.Column('check_out_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_inscricao'], ['inscricao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_inscricao')
    )
    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.alter_column('status_inscricao',
               existing_type=mysql.ENUM('pendente', 'aprovado', 'rejeitado'),
               type_=sa.Enum('pendente', 'aprovada', 'recusada', name='statusinscricao'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('inscricao_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'oportunidade', ['id_oportunidade'], ['id'])
        batch_op.drop_column('id_inscricao')

    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('id_organizacao', sa.Integer(), nullable=False))
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('aberto', 'fechado'),
               type_=sa.Enum('aberta', 'fechada', name='statusoportunidades'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('oportunidade_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'organizacao', ['id_organizacao'], ['id'])
        batch_op.drop_column('organizaçao_id')
        batch_op.drop_column('requisitos')
        batch_op.drop_column('id_oportunidade')

    with op.batch_alter_table('organizacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('cnpj', sa.String(length=14), nullable=False))
        batch_op.alter_column('aprovada',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Enum('pendente', 'aprovada', 'recusada', name='statusorganizacao'),
               nullable=False)
        batch_op.drop_index(batch_op.f('cnpj_id'))
        batch_op.create_unique_constraint(None, ['cnpj'])
        batch_op.drop_column('id_organizacao')
        batch_op.drop_column('cnpj_id')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('habilidades')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habilidades', mysql.JSON(), nullable=True))

    with op.batch_alter_table('organizacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj_id', mysql.VARCHAR(length=14), nullable=False))
        batch_op.add_column(sa.Column('id_organizacao', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('cnpj_id'), ['cnpj_id'], unique=True)
        batch_op.alter_column('aprovada',
               existing_type=sa.Enum('pendente', 'aprovada', 'recusada', name='statusorganizacao'),
               type_=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.drop_column('cnpj')
        batch_op.drop_column('id')

    with op.batch_alter_table('oportunidade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_oportunidade', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('requisitos', mysql.VARCHAR(length=1024), nullable=True))
        batch_op.add_column(sa.Column('organizaçao_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('oportunidade_ibfk_1'), 'organizacao', ['organizaçao_id'], ['id_organizacao'])
        batch_op.alter_column('status',
               existing_type=sa.Enum('aberta', 'fechada', name='statusoportunidades'),
               type_=mysql.ENUM('aberto', 'fechado'),
               existing_nullable=False)
        batch_op.drop_column('id_organizacao')
        batch_op.drop_column('id')

    with op.batch_alter_table('inscricao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_inscricao', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('inscricao_ibfk_1'), 'oportunidade', ['id_oportunidade'], ['id_oportunidade'])
        batch_op.alter_column('status_inscricao',
               existing_type=sa.Enum('pendente', 'aprovada', 'recusada', name='statusinscricao'),
               type_=mysql.ENUM('pendente', 'aprovado', 'rejeitado'),
               existing_nullable=False)
        batch_op.drop_column('id')

    op.drop_table('registro_presenca')
    op.drop_table('oportunidade_habilidade')
    op.drop_table('voluntario_habilidade')
    op.drop_table('habilidade')
    # ### end Alembic commands ###
