"""json nas habilidades

Revision ID: ecd77292847f
Revises: 24be6e8c47e2
Create Date: 2025-11-04 23:11:51.775780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecd77292847f'
down_revision = '24be6e8c47e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('habilidades',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('habilidades',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###
