"""Migracao inicial corrigida

Revision ID: f3c560ec7c3e
Revises: 
Create Date: 2025-11-11 13:40:19.947268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c560ec7c3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome_completo', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('bairro', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('data_nasc', sa.Date(), nullable=False),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('tipo_usuario', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('conta_ativa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('organizacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_responsavel', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=1024), nullable=False),
    sa.Column('email_institucional', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('descricao', sa.String(length=2048), nullable=True),
    sa.Column('endereco_matriz', sa.String(length=255), nullable=False),
    sa.Column('contato', sa.String(length=11), nullable=False),
    sa.Column('documento', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('aprovada', sa.Enum('pendente', 'aprovada', 'recusada', name='statusorganizacao'), nullable=False),
    sa.ForeignKeyConstraint(['id_responsavel'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email_institucional')
    )
    op.create_table('voluntario_habilidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_habilidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_habilidade'], ['habilidade.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_usuario', 'id_habilidade', name='uq_usuario_habilidade')
    )
    op.create_table('oportunidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_organizacao', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=2048), nullable=False),
    sa.Column('local_endereco', sa.String(length=255), nullable=False),
    sa.Column('comunidade', sa.String(length=255), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('duracao_horas', sa.Integer(), nullable=False),
    sa.Column('num_vagas', sa.Integer(), nullable=False),
    sa.Column('tags', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('aberta', 'fechada', name='statusoportunidades'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_organizacao'], ['organizacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inscricao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_oportunidade', sa.Integer(), nullable=False),
    sa.Column('data_inscricao', sa.DateTime(), nullable=True),
    sa.Column('status_inscricao', sa.Enum('pendente', 'aprovada', 'recusada', name='statusinscricao'), nullable=False),
    sa.Column('data_aprovacao_recusa', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_oportunidade'], ['oportunidade.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oportunidade_habilidade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_oportunidade', sa.Integer(), nullable=False),
    sa.Column('id_habilidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_habilidade'], ['habilidade.id'], ),
    sa.ForeignKeyConstraint(['id_oportunidade'], ['oportunidade.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_oportunidade', 'id_habilidade', name='uq_oportunidade_habilidade')
    )
    op.create_table('registro_presenca',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_inscricao', sa.Integer(), nullable=False),
    sa.Column('codigo_validacao_pin', sa.String(length=100), nullable=False),
    sa.Column('check_in_hora', sa.DateTime(), nullable=True),
    sa.Column('check_out_hora', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_inscricao'], ['inscricao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_inscricao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_presenca')
    op.drop_table('oportunidade_habilidade')
    op.drop_table('inscricao')
    op.drop_table('oportunidade')
    op.drop_table('voluntario_habilidade')
    op.drop_table('organizacao')
    op.drop_table('usuario')
    op.drop_table('habilidade')
    # ### end Alembic commands ###
